[env:blackpill_f401cc]
platform = ststm32
board = blackpill_f401cc
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
board_build.ldscript = STM32F401CCUx_FLASH.ld
monitor_speed = 115200
build_flags =
	-I Core/Inc
	-D USE_HAL_DRIVER
	-D STM32F401xC
	-Wall
	-Wextra
	-Wno-unused-parameter
	-Wno-missing-field-initializers

[platformio]
default_envs = blackpill_f401cc
src_dir = Core/Src